// wrapper_assistant/src/components/Launcher.tsx
import React, { useEffect, useState } from 'react';
import { Menu, List, Typography, Avatar, Spin, message } from 'antd';
import { fetchLaunchConfig, LaunchConfig, LaunchItem } from '../api';
import './Launcher.less';

const { Title } = Typography;

const Launcher: React.FC = () => {
  const [config, setConfig] = useState<LaunchConfig | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchLaunchConfig()
      .then(cfg => {
        setConfig(cfg);
        setSelectedCategory(cfg.categories[0] || '');
      })
      .catch(() => {
        message.error('获取启动项配置失败');
      })
      .finally(() => setLoading(false));
  }, []);

  const handleMenuClick = (e: any) => {
    setSelectedCategory(e.key);
  };

  const getItemsByCategory = (category: string): LaunchItem[] => {
    if (!config) return [];
    return config.items.filter(item => item.category === category);
  };

  if (loading) {
    return <div style={{textAlign: 'center', marginTop: 100}}><Spin size="large" /></div>;
  }

  if (!config) {
    return <div style={{textAlign: 'center', marginTop: 100}}>配置加载失败</div>;
  }

  return (
    <div className="launcher">
      {/* 顶部标题栏 */}
      <div className="launcher-header">
        <Title level={3} style={{ margin: 0, padding: '12px 24px' }}>Poner</Title>
      </div>
      <div className="launcher-body">
        {/* 左侧分类菜单 */}
        <div className="menu">
          <Menu onClick={handleMenuClick} selectedKeys={[selectedCategory]} mode="inline">
            {config.categories.map((category) => (
              <Menu.Item key={category}>{category}</Menu.Item>
            ))}
          </Menu>
        </div>
        {/* 右侧启动项列表 */}
        <div className="list">
          <List
            header={<div style={{ fontWeight: 600, fontSize: 16 }}>{selectedCategory}</div>}
            itemLayout="horizontal"
            dataSource={getItemsByCategory(selectedCategory)}
            renderItem={(item: LaunchItem) => {
              let avatarSrc: string | undefined = undefined;
              if (item.icon_base64 && item.icon_base64.startsWith('data:image')) {
                avatarSrc = item.icon_base64;
              } else if (item.icon_location && (item.icon_location.startsWith('http://') || item.icon_location.startsWith('https://'))) {
                avatarSrc = item.icon_location;
              }
              return (
                <List.Item>
                  <List.Item.Meta
                    avatar={<Avatar src={avatarSrc}>{!avatarSrc && item.name[0]}</Avatar>}
                    title={item.name}
                    description={item.target_path}
                  />
                </List.Item>
              );
            }}
          />
        </div>
      </div>
    </div>
  );
};

export default Launcher;

// wrapper_assistant/src/components/Launcher.vue
<template>
  <div class="launcher">
    <div class="launcher-header">
      <a-typography-title :level="3" style="margin:0;padding:12px 24px;">Poner</a-typography-title>
    </div>
    <div class="launcher-body">
      <div class="menu">
        <a-menu :selectedKeys="[selectedCategory]" mode="inline" @click="handleMenuClick">
          <a-menu-item v-for="category in config?.categories || []" :key="category">{{ category }}</a-menu-item>
        </a-menu>
      </div>
      <div class="list">
        <a-list
          :header="selectedCategory"
          item-layout="horizontal"
          :data-source="getItemsByCategory(selectedCategory)"
        >
          <template #renderItem="{ item }">
            <a-list-item>
              <a-list-item-meta
                :avatar="getAvatar(item)"
                :title="item.name"
                :description="item.target_path"
              />
            </a-list-item>
          </template>
        </a-list>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { message, List as AList, Menu as AMenu, Typography as ATypography, Avatar as AAvatar, Spin as ASpin } from 'ant-design-vue';
import { fetchLaunchConfig } from '../api';
import './Launcher.less';

const config = ref<any>(null);
const selectedCategory = ref('');
const loading = ref(true);

onMounted(async () => {
  try {
    const cfg = await fetchLaunchConfig();
    config.value = cfg;
    selectedCategory.value = cfg.categories[0] || '';
  } catch {
    message.error('获取启动项配置失败');
  } finally {
    loading.value = false;
  }
});

function handleMenuClick({ key }: any) {
  selectedCategory.value = key;
}
function getItemsByCategory(category: string) {
  if (!config.value) return [];
  return config.value.items.filter((item: any) => item.category === category);
}
function getAvatar(item: any) {
  let avatarSrc: string | undefined = undefined;
  if (item.icon_base64 && item.icon_base64.startsWith('data:image')) {
    avatarSrc = item.icon_base64;
  } else if (item.icon_location && (item.icon_location.startsWith('http://') || item.icon_location.startsWith('https://'))) {
    avatarSrc = item.icon_location;
  }
  return avatarSrc ? <a-avatar src={avatarSrc}>{!avatarSrc && item.name[0]}</a-avatar> : <a-avatar>{item.name[0]}</a-avatar>;
}
</script>
